# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title
encoding: utf-8

exclude: [".ruby-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge

timezone: UTC
markdown: kramdown

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title: Leopard Blog
tagline: "Anything is possible, the impossible becomes longer"
author:
  name: Alexey Vasiliev
  email: "leopard_ne[at]inbox.ru"
  github: le0pard
  twitter: leopard_me
  feedburner: ualeopard

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
baseurl: ""
url: "http://leopard.in.ua"

archive_path: /archive.html
pages_path: /pages.html
categories_path: /categories.html
tags_path: /tags.html

sass:
  sass_dir: _includes/sass
  style: :compressed

comments:
  disqus_short_name: "le0pardblog"

sharing:
  facebook_app_id: "1049019491883663"

analytics:
  google_tracking_id: "UA-7068020-1"

webtools:
  google_webmasters_id: "9PT3i6suRtibkvkQAJMs90s4u0qL1TQnfAe6HCE1_Fs"
